### ISSUE TITLE
Documentation for branching needs more love

### ISSUE THREAD

**Issue by 12Balu34** [vmware/ansible-for-nsxt#266]
Hi,

first of all, thank you for your work. Using these modules make life much easier for us compared to simply using REST calls. Please regard the following remarks as constructive criticism.

I'd like to readdress #257 (which branch do use with which NSX-T Release).
Although you thankfully  provided an answer in the issue, imho you should **not only** document that in an issue.   

For people who start using the modules, the README of your default branch (`master` at the moment) will be the first point of entry. The information is still missing there.  
It seems that your master ***should not*** be used as of now. You might consider [switching your default branch](https://help.github.com/en/enterprise/2.13/user/articles/setting-the-default-branch) to the lastest "release branch" temporarily.  
 
Also I'd like to kindly ask about your branching strategy for the future.
* Will the branches be maintained?  It doesn't seem that way, given that the last commit on branch `v1.1.0` dates back to 3 Oct 2019.
* How do you plan to bring bug fixes to existing "releases"? Will bug fixes be merged at all? If so, into which branch?
* If I want to contribute, which branch should I create Pull-Requests for?
* Why is there a separate branch for each release? Please consider keeping the latest version on `master` while using tags and [GitHub Releases](https://help.github.com/en/enterprise/2.13/user/articles/creating-releases)  to track changes and releases. 

Versioning the modules we use is vital to operations for us. Some clarification on the questions above is highly appreciated. I'd be happy to document the answers by creating a pull request.

**Comment by BlueArcherX** [comment]
I would have to agree with this. It this repo feels very confusing most of the time and @12Balu34 sums up my feelings completely.

**Comment by riverwolf67** [comment]
Bump. Agree w @12Balu34!

**Comment by tvigneron** [comment]
Hello 12Balu34, BlueArcherX and riverwolf67

Thank you for the feedback, I agree we need to improve this Github organization and branching.
While for now Madhu status from #257 still holds we are working on:
- Merge Master and Dev branches. Have Master be both the first point of entry and the latest version of the development.
- Cut branches when we publish a validated and tested version. 
Those are published also on NSX-T driver and tools page ([page](https://my.vmware.com/en/web/vmware/info/slug/networking_security/vmware_nsx_t_data_center/3_x#drivers_tools)) and typically support N and N-1 versions of NSX-T (there's a release note).
- Update the readmes.

To make sure I completely answer your questions:

Will the branches be maintained? It doesn't seem that way, given that the last commit on branch v1.1.0 dates back to 3 Oct 2019.
[Answer] Once a branch has been cut for a given version there won't be any additional features added to it. Only bug fixes would be added to this branch.
This maps to the code released for a given NSX-T release and described in the release note in Driver and Tools on VMware download page. The main point being that this code has been reviewed, tested and validated by QE.

How do you plan to bring bug fixes to existing "releases"? Will bug fixes be merged at all? If so, into which branch?
[Answer] Bug fixes on released branch (example: v3.0.0) will be fixed on the branch (v3.0.0) and also pushed to dev branch (master branch when dev/master merge is finished)

If I want to contribute, which branch should I create Pull-Requests for?
[Answer]  As of now its better to open the pull request on the dev branch (until we merge dev and master and have one branch)

Why is there a separate branch for each release? Please consider keeping the latest version on master while using tags and GitHub Releases to track changes and releases.
[Answer] The latest version will be on master, the branching is just done so that people less familiar with GitHub can easily get the "validated" modules.

For the versioning, it appeared clearer to map the version to the NSX-T release than to have a distinct versioning for Ansible Modules. The rule is that the modules will support the N and N-1 release of NSX-T.  (If some features are only available in the N version we will call them out).

Hoping this clarifies it.

**Comment by 12Balu34** [comment]
I think it clears up most the questions I had, let's see how the restructuring will turn out.
Thank you for your answer @tvigneron !

**Comment by madhukark** [comment]
Hello All,

The merging of the branches and restructuring has been done. Thank you all for your patience in this regard. Here is the new structure with some answers from @tvigneron consolidated here:

- `master` is the main development branch
- All pull requests will be against `master`. Pull requests to other released versioned branches (example: v3.0.0) will not be accepted
- Once a branch has been cut for a given version there won't be any additional features added to it. Only bug fixes would be added to this branch
- Bug fixes on released branch (example: v3.0.0) will be fixed on the branch (v3.0.0) and also pushed to `master` branch

Thank you
