### ISSUE TITLE
nsxt-datacenter-ci-pipelines no longer works

### ISSUE THREAD

**Issue by lamlouis** [vmware/ansible-for-nsxt#45]
it appears that the most recent changes broke the pipeline https://github.com/vmware/nsx-t-datacenter-ci-pipelines. I'm now getting errors like these below in the pipeline. 

```
The error appears to have been in '/tmp/build/6fab756d/nsxt-ansible/basic_topology.yml': line 143, column 7, but may be elsewhere in the file depending on the exact syntax problem.	

The offending line appears to be:
    - name: Deploy controller
	
      ^ here
```

**Comment by Dyanngg** [comment]
@lamlouis 'nxt_controller' ansible module has been moved to 'nsxt_controller_manager_auto_deployment', since as of NSX-T 2.4.0 controllers and managers will be on the same node. We are currently testing this change on nsx-t-datacenter-ci-pipelines/unified_appliance branch. Waiting on @r-raghu for backward compatibility asks.

**Comment by Akhilesh2412** [comment]
We have cut the NSX-T 2.3.0 supported branch to ansible v1.0.0. and for NSX-T 2.4.0 we have v1.1.0 branch. Currently, the master branch contains the latest release. (i.e. 2.4.0).  So if you are consuming NSX-T 2.3.0 related module please use v1.0.0 branch.
